"""Single source of truth for a paper's run-directory layout.

One directory per paper, numbered by pipeline stage so that ``ls`` reads in
data-flow order and an agent landing in the dir has a deterministic reading
order::

    runs/<paper_id>/
      README.md            # human index (this file is generated)
      CLAIMS.md            # human-readable selected claim + implementation list
      manifest.json        # machine index (generated by scanning the tree)
      00-parse/            # url/pdf -> paper.md + figures/ + figures.index.json (MinerU)
      01-extract/          # paper -> claims      (extract + triage)
      02-spec/             # claim -> spec        (<claim_id>.<hash>.yaml)
      03-task/<claim_id>/<hash>/  # spec -> task bundle (input_files/, reward/)
      04-run/<claim_id>/<hash>/NNN/   # task -> attempts (run.json, agent.log,
                               #   workspace/, trajectory/)

Every stage builds its paths through :class:`PaperLayout` so the convention is
defined in exactly one place and cannot drift. :func:`write_index` regenerates
``manifest.json`` + ``README.md`` from whatever is actually on disk, so the
index never lies.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

LAYOUT_VERSION = 1

PARSE = "00-parse"
EXTRACT = "01-extract"
SPEC = "02-spec"
TASK = "03-task"
RUN = "04-run"

_STAGE_DESC = {
    PARSE: "paper source (url/pdf) -> structured markdown + local figures (MinerU)",
    EXTRACT: "paper -> claims (extract + triage)",
    SPEC: "claim -> canonical spec",
    TASK: "spec -> rendered task bundle (input_files/ + hidden reward/)",
    RUN: "task -> reproduction attempts (workspace/ + trajectory/)",
}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass(frozen=True)
class PaperLayout:
    """Path arithmetic for one paper's run directory."""

    root: Path

    @classmethod
    def for_paper(cls, runs_root: str | Path, paper_id: str) -> "PaperLayout":
        return cls(Path(runs_root) / paper_id)

    @classmethod
    def from_task_dir(cls, task_dir: str | Path) -> "PaperLayout | None":
        """Recover the paper layout from old or hash-versioned task paths."""
        task_dir = Path(task_dir)
        if task_dir.parent.name == TASK:
            return cls(task_dir.parent.parent)
        if task_dir.parent.parent.name == TASK:
            return cls(task_dir.parent.parent.parent)
        return None

    # ---- stage directories -------------------------------------------------
    @property
    def parse_dir(self) -> Path:
        return self.root / PARSE

    @property
    def parsed_paper_path(self) -> Path:
        return self.parse_dir / "paper.md"

    @property
    def parsed_figures_dir(self) -> Path:
        return self.parse_dir / "figures"

    @property
    def figure_index_path(self) -> Path:
        return self.parse_dir / "figures.index.json"

    @property
    def extract_dir(self) -> Path:
        return self.root / EXTRACT

    @property
    def spec_dir(self) -> Path:
        return self.root / SPEC

    @property
    def task_root(self) -> Path:
        return self.root / TASK

    @property
    def run_root(self) -> Path:
        return self.root / RUN

    @property
    def paper_path(self) -> Path:
        return self.root / "paper.md"

    @property
    def manifest_path(self) -> Path:
        return self.root / "manifest.json"

    @property
    def readme_path(self) -> Path:
        return self.root / "README.md"

    @property
    def claims_md_path(self) -> Path:
        return self.root / "CLAIMS.md"

    # ---- per-claim paths ---------------------------------------------------
    def spec_path(self, claim_id: str, spec_hash: str | None = None) -> Path:
        suffix = f".{spec_hash}" if spec_hash else ""
        return self.spec_dir / f"{claim_id}{suffix}.yaml"

    def task_dir(self, claim_id: str, spec_hash: str | None = None) -> Path:
        base = self.task_root / claim_id
        return base / spec_hash if spec_hash else base

    def run_base(self, claim_id: str, spec_hash: str | None = None) -> Path:
        base = self.run_root / claim_id
        return base / spec_hash if spec_hash else base

    def next_run_dir(self, claim_id: str, spec_hash: str | None = None) -> Path:
        """Return the next ``NNN`` attempt dir for a claim (001, 002, ...)."""
        base = self.run_base(claim_id, spec_hash)
        base.mkdir(parents=True, exist_ok=True)
        existing = [
            int(p.name)
            for p in base.iterdir()
            if p.is_dir() and p.name.isdigit()
        ]
        n = (max(existing) + 1) if existing else 1
        return base / f"{n:03d}"


def _safe_load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def build_manifest(layout: PaperLayout, *, paper_id: str | None = None) -> dict[str, Any]:
    """Scan the layout and produce an accurate machine-readable index."""
    selected_doc = _safe_load_json(layout.extract_dir / "selected_claims_for_build.json")
    legacy_claims_doc = _safe_load_json(layout.extract_dir / "claims.json")
    legacy_selected_doc = _safe_load_json(layout.extract_dir / "selected_claims.json")
    candidate_doc = _safe_load_json(layout.extract_dir / "candidate_claims.json")
    claims = (
        [c.get("claim_id") for c in selected_doc if isinstance(c, dict)]
        if isinstance(selected_doc, list)
        else [c.get("claim_id") for c in legacy_selected_doc if isinstance(c, dict)]
        if isinstance(legacy_selected_doc, list)
        else [c.get("claim_id") for c in legacy_claims_doc if isinstance(c, dict)]
        if isinstance(legacy_claims_doc, list)
        else []
    )
    candidate_claims = (
        [c.get("claim_id") for c in candidate_doc if isinstance(c, dict)]
        if isinstance(candidate_doc, list)
        else claims
    )

    specs = sorted(p.stem for p in layout.spec_dir.glob("*.yaml")) if layout.spec_dir.is_dir() else []
    tasks: list[str] = []
    stale_tasks: list[str] = []
    selected_set = {str(c) for c in claims}
    task_records: list[tuple[str, str, float]] = []
    if layout.task_root.is_dir():
        for claim_dir in sorted(p for p in layout.task_root.iterdir() if p.is_dir()):
            data_entry = claim_dir / "data_entry.json"
            if data_entry.is_file():
                task_records.append((claim_dir.name, claim_dir.name, data_entry.stat().st_mtime))
                continue
            for hash_dir in sorted(p for p in claim_dir.iterdir() if p.is_dir()):
                data_entry = hash_dir / "data_entry.json"
                if data_entry.is_file():
                    key = f"{claim_dir.name}/{hash_dir.name}"
                    task_records.append((claim_dir.name, key, data_entry.stat().st_mtime))
    latest_by_claim: dict[str, tuple[str, float]] = {}
    for claim_id, key, mtime in task_records:
        if claim_id not in selected_set:
            stale_tasks.append(key)
            continue
        old = latest_by_claim.get(claim_id)
        if old is None or mtime > old[1]:
            latest_by_claim[claim_id] = (key, mtime)
    active_keys = {rec[0] for rec in latest_by_claim.values()}
    for claim_id, key, _mtime in task_records:
        if claim_id in selected_set and key not in active_keys:
            stale_tasks.append(key)
    tasks = sorted(active_keys)
    stale_tasks = sorted(stale_tasks)

    runs: dict[str, list[dict[str, Any]]] = {}
    if layout.run_root.is_dir():
        for claim_dir in sorted(layout.run_root.iterdir()):
            if not claim_dir.is_dir():
                continue
            candidates: list[tuple[str, Path]] = []
            if any(p.is_dir() and p.name.isdigit() for p in claim_dir.iterdir()):
                candidates.append((claim_dir.name, claim_dir))
            else:
                for hash_dir in sorted(p for p in claim_dir.iterdir() if p.is_dir()):
                    candidates.append((f"{claim_dir.name}/{hash_dir.name}", hash_dir))
            for key, base_dir in candidates:
                attempts = []
                for run_dir in sorted(base_dir.iterdir()):
                    if not run_dir.is_dir():
                        continue
                    rec = _safe_load_json(run_dir / "run.json") or {}
                    attempts.append(
                        {
                            "id": run_dir.name,
                            "status": rec.get("status"),
                            "reward": rec.get("reward"),
                            "backend": rec.get("backend"),
                            "ended_at": rec.get("ended_at"),
                            "spec_hash": rec.get("spec_hash"),
                        }
                    )
                if attempts:
                    runs[key] = attempts

    task_by_claim: dict[str, str] = {}
    for task in tasks:
        claim_id = task.split("/", 1)[0]
        task_by_claim.setdefault(claim_id, task)

    selected_table_doc = (
        selected_doc
        if isinstance(selected_doc, list)
        else legacy_selected_doc
        if isinstance(legacy_selected_doc, list)
        else legacy_claims_doc
        if isinstance(legacy_claims_doc, list)
        else []
    )
    claim_table: list[dict[str, Any]] = []
    if isinstance(selected_table_doc, list):
        for claim in selected_table_doc:
            if not isinstance(claim, dict):
                continue
            claim_id = str(claim.get("claim_id") or "")
            claim_table.append(
                {
                    "claim_id": claim_id,
                    "display_title": claim.get("display_title"),
                    "statement": claim.get("statement"),
                    "claim_type": claim.get("claim_type"),
                    "cost": claim.get("cost"),
                    "requires_training": claim.get("requires_training"),
                    "verifiability": claim.get("verifiability"),
                    "selection_rank": claim.get("selection_rank"),
                    "selection_score": claim.get("selection_score"),
                    "selection_reason": claim.get("selection_reason"),
                    "required_experiments": claim.get("required_experiments") or [],
                    "intermediate_steps": claim.get("intermediate_steps") or [],
                    "implementation_notes": claim.get("implementation_notes") or claim.get("notes"),
                    "task": task_by_claim.get(claim_id),
                }
            )

    return {
        "paper_id": paper_id or layout.root.name,
        "layout_version": LAYOUT_VERSION,
        "generated_at": _now_iso(),
        "has_parsed_bundle": layout.parsed_paper_path.is_file(),
        "has_paper_snapshot": layout.paper_path.is_file(),
        "has_token_usage": (layout.root / "token_usage.jsonl").is_file(),
        "has_token_usage_summary": (layout.root / "token_usage.summary.json").is_file(),
        "claims": claims,
        "candidate_claims": candidate_claims,
        "specs": specs,
        "tasks": tasks,
        "stale_tasks": stale_tasks,
        "claim_table": claim_table,
        "runs": runs,
    }


def _best_reward(attempts: list[dict[str, Any]]) -> Any:
    rewards = [a["reward"] for a in attempts if isinstance(a.get("reward"), (int, float))]
    return max(rewards) if rewards else None


def render_readme(manifest: dict[str, Any]) -> str:
    """Render a concise, human-friendly index from the manifest."""
    paper_id = manifest.get("paper_id", "?")
    lines: list[str] = [
        f"# Reproduction run: `{paper_id}`",
        "",
        f"_Generated {manifest.get('generated_at', '?')} (layout v{manifest.get('layout_version')})._",
        "",
        "Read top-to-bottom = pipeline order. `manifest.json` is the machine-readable index.",
        "See `CLAIMS.md` for the selected claim and implementation list.",
        "",
        "## Stages",
        "",
        f"- `{PARSE}/` — {_STAGE_DESC[PARSE]}",
        f"- `{EXTRACT}/` — {_STAGE_DESC[EXTRACT]}",
        f"- `{SPEC}/` — {_STAGE_DESC[SPEC]}",
        f"- `{TASK}/` — {_STAGE_DESC[TASK]}",
        f"- `{RUN}/` — {_STAGE_DESC[RUN]}",
        "",
        "## Status",
        "",
        f"- selected claims: **{len(manifest.get('claims', []))}**"
        f" ({', '.join(manifest.get('claims', [])) or '—'})",
        f"- candidate claims: **{len(manifest.get('candidate_claims', []))}**",
        f"- specs built: **{len(manifest.get('specs', []))}**",
        f"- active tasks rendered: **{len(manifest.get('tasks', []))}**",
        f"- stale/historical tasks: **{len(manifest.get('stale_tasks', []))}**",
        f"- token usage: **{'yes' if manifest.get('has_token_usage') else 'no'}**",
        "",
    ]

    runs = manifest.get("runs", {})
    if runs:
        lines += ["### Runs", "", "| claim | attempts | best reward | latest status |", "|---|---|---|---|"]
        for claim_id, attempts in runs.items():
            best = _best_reward(attempts)
            latest = attempts[-1].get("status") if attempts else None
            lines.append(
                f"| `{claim_id}` | {len(attempts)} | {best if best is not None else '—'} "
                f"| {latest or '—'} |"
            )
        lines.append("")
    else:
        lines += ["### Runs", "", "_No attempts yet._", ""]

    return "\n".join(lines)


def _md_cell(value: Any) -> str:
    text = "—" if value in (None, "") else str(value)
    return text.replace("|", "\\|").replace("\n", "<br>")


def _bullet_lines(items: list[Any]) -> list[str]:
    lines = []
    for item in items:
        if isinstance(item, dict):
            label = item.get("label") or item.get("name") or item.get("condition")
            desc = item.get("description") or item.get("value") or item.get("note") or item
            lines.append(f"- {label}: {desc}" if label else f"- {desc}")
        else:
            lines.append(f"- {item}")
    return lines


def render_claims_md(manifest: dict[str, Any]) -> str:
    """Render selected claims and implementation hints for human review."""
    paper_id = manifest.get("paper_id", "?")
    rows = manifest.get("claim_table") or []
    lines: list[str] = [
        f"# Selected Claims: `{paper_id}`",
        "",
        "This file is generated from `selected_claims_for_build.json` and the rendered task index.",
        "",
    ]
    if not rows:
        return "\n".join(lines + ["_No selected claims yet._", ""])

    lines += [
        "## Overview",
        "",
        "| rank | claim | type | cost | training | score | task |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    _md_cell(row.get("selection_rank")),
                    f"`{_md_cell(row.get('claim_id'))}`<br>{_md_cell(row.get('display_title'))}",
                    _md_cell(row.get("claim_type")),
                    _md_cell(row.get("cost")),
                    _md_cell(row.get("requires_training")),
                    _md_cell(row.get("selection_score")),
                    f"`{_md_cell(row.get('task'))}`" if row.get("task") else "—",
                ]
            )
            + " |"
        )
    lines.append("")

    for row in rows:
        claim_id = row.get("claim_id") or "claim"
        title = row.get("display_title") or claim_id
        lines += [
            f"## `{claim_id}` — {title}",
            "",
            f"**Statement.** {row.get('statement') or '—'}",
            "",
            f"**Selection.** {row.get('selection_reason') or '—'}",
            "",
            f"**Task.** `{row.get('task') or '—'}`",
            "",
            "### Implementation",
            "",
        ]
        required = _bullet_lines(list(row.get("required_experiments") or []))
        steps = _bullet_lines(list(row.get("intermediate_steps") or []))
        if required:
            lines += ["Required experiments:", *required, ""]
        if steps:
            lines += ["Intermediate steps:", *steps, ""]
        notes = row.get("implementation_notes")
        if notes:
            lines += ["Implementation notes:", "", str(notes), ""]
        if not required and not steps and not notes:
            lines += ["_No implementation notes were extracted._", ""]
    return "\n".join(lines)


def write_index(layout: PaperLayout, *, paper_id: str | None = None) -> dict[str, Any]:
    """Regenerate manifest.json + README.md from the current tree. Returns the manifest."""
    layout.root.mkdir(parents=True, exist_ok=True)
    manifest = build_manifest(layout, paper_id=paper_id)
    layout.manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    layout.readme_path.write_text(render_readme(manifest), encoding="utf-8")
    layout.claims_md_path.write_text(render_claims_md(manifest), encoding="utf-8")
    return manifest


def write_run_record(run_dir: str | Path, record: dict[str, Any]) -> Path:
    """Persist a run's metadata as run.json (status/reward/backend/timestamps)."""
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    path = run_dir / "run.json"
    path.write_text(
        json.dumps({"generated_at": _now_iso(), **record}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return path
