"""Single source of truth for a paper's run-directory layout.

One directory per paper, numbered by pipeline stage so that ``ls`` reads in
data-flow order and an agent landing in the dir has a deterministic reading
order::

    runs/<paper_id>/
      README.md            # human index (this file is generated)
      manifest.json        # machine index (generated by scanning the tree)
      paper.md             # snapshot of the source paper
      01-extract/          # paper -> claims      (extract + triage)
      02-spec/             # claim -> spec        (<claim_id>.yaml)
      03-task/<claim_id>/  # spec  -> task bundle (input_files/, reward/)
      04-run/<claim_id>/NNN/   # task -> attempts (run.json, agent.log,
                               #   workspace/, trajectory/)

Every stage builds its paths through :class:`PaperLayout` so the convention is
defined in exactly one place and cannot drift. :func:`write_index` regenerates
``manifest.json`` + ``README.md`` from whatever is actually on disk, so the
index never lies.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

LAYOUT_VERSION = 1

EXTRACT = "01-extract"
SPEC = "02-spec"
TASK = "03-task"
RUN = "04-run"

_STAGE_DESC = {
    EXTRACT: "paper -> claims (extract + triage)",
    SPEC: "claim -> canonical spec",
    TASK: "spec -> rendered task bundle (input_files/ + hidden reward/)",
    RUN: "task -> reproduction attempts (workspace/ + trajectory/)",
}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass(frozen=True)
class PaperLayout:
    """Path arithmetic for one paper's run directory."""

    root: Path

    @classmethod
    def for_paper(cls, runs_root: str | Path, paper_id: str) -> "PaperLayout":
        return cls(Path(runs_root) / paper_id)

    @classmethod
    def from_task_dir(cls, task_dir: str | Path) -> "PaperLayout | None":
        """Recover the paper layout from a ``.../03-task/<claim_id>`` path."""
        task_dir = Path(task_dir)
        if task_dir.parent.name == TASK:
            return cls(task_dir.parent.parent)
        return None

    # ---- stage directories -------------------------------------------------
    @property
    def extract_dir(self) -> Path:
        return self.root / EXTRACT

    @property
    def spec_dir(self) -> Path:
        return self.root / SPEC

    @property
    def task_root(self) -> Path:
        return self.root / TASK

    @property
    def run_root(self) -> Path:
        return self.root / RUN

    @property
    def paper_path(self) -> Path:
        return self.root / "paper.md"

    @property
    def manifest_path(self) -> Path:
        return self.root / "manifest.json"

    @property
    def readme_path(self) -> Path:
        return self.root / "README.md"

    # ---- per-claim paths ---------------------------------------------------
    def spec_path(self, claim_id: str) -> Path:
        return self.spec_dir / f"{claim_id}.yaml"

    def task_dir(self, claim_id: str) -> Path:
        return self.task_root / claim_id

    def run_base(self, claim_id: str) -> Path:
        return self.run_root / claim_id

    def next_run_dir(self, claim_id: str) -> Path:
        """Return the next ``NNN`` attempt dir for a claim (001, 002, ...)."""
        base = self.run_base(claim_id)
        base.mkdir(parents=True, exist_ok=True)
        existing = [
            int(p.name)
            for p in base.iterdir()
            if p.is_dir() and p.name.isdigit()
        ]
        n = (max(existing) + 1) if existing else 1
        return base / f"{n:03d}"


def _safe_load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def build_manifest(layout: PaperLayout, *, paper_id: str | None = None) -> dict[str, Any]:
    """Scan the layout and produce an accurate machine-readable index."""
    claims_doc = _safe_load_json(layout.extract_dir / "claims.json")
    claims = (
        [c.get("claim_id") for c in claims_doc if isinstance(c, dict)]
        if isinstance(claims_doc, list)
        else []
    )

    specs = sorted(p.stem for p in layout.spec_dir.glob("*.yaml")) if layout.spec_dir.is_dir() else []
    tasks = (
        sorted(p.name for p in layout.task_root.iterdir() if p.is_dir())
        if layout.task_root.is_dir()
        else []
    )

    runs: dict[str, list[dict[str, Any]]] = {}
    if layout.run_root.is_dir():
        for claim_dir in sorted(layout.run_root.iterdir()):
            if not claim_dir.is_dir():
                continue
            attempts = []
            for run_dir in sorted(claim_dir.iterdir()):
                if not run_dir.is_dir():
                    continue
                rec = _safe_load_json(run_dir / "run.json") or {}
                attempts.append(
                    {
                        "id": run_dir.name,
                        "status": rec.get("status"),
                        "reward": rec.get("reward"),
                        "backend": rec.get("backend"),
                        "ended_at": rec.get("ended_at"),
                    }
                )
            if attempts:
                runs[claim_dir.name] = attempts

    return {
        "paper_id": paper_id or layout.root.name,
        "layout_version": LAYOUT_VERSION,
        "generated_at": _now_iso(),
        "has_paper_snapshot": layout.paper_path.is_file(),
        "claims": claims,
        "specs": specs,
        "tasks": tasks,
        "runs": runs,
    }


def _best_reward(attempts: list[dict[str, Any]]) -> Any:
    rewards = [a["reward"] for a in attempts if isinstance(a.get("reward"), (int, float))]
    return max(rewards) if rewards else None


def render_readme(manifest: dict[str, Any]) -> str:
    """Render a concise, human-friendly index from the manifest."""
    paper_id = manifest.get("paper_id", "?")
    lines: list[str] = [
        f"# Reproduction run: `{paper_id}`",
        "",
        f"_Generated {manifest.get('generated_at', '?')} (layout v{manifest.get('layout_version')})._",
        "",
        "Read top-to-bottom = pipeline order. `manifest.json` is the machine-readable index.",
        "",
        "## Stages",
        "",
        f"- `{EXTRACT}/` — {_STAGE_DESC[EXTRACT]}",
        f"- `{SPEC}/` — {_STAGE_DESC[SPEC]}",
        f"- `{TASK}/` — {_STAGE_DESC[TASK]}",
        f"- `{RUN}/` — {_STAGE_DESC[RUN]}",
        "",
        "## Status",
        "",
        f"- claims extracted: **{len(manifest.get('claims', []))}**"
        f" ({', '.join(manifest.get('claims', [])) or '—'})",
        f"- specs built: **{len(manifest.get('specs', []))}**",
        f"- tasks rendered: **{len(manifest.get('tasks', []))}**",
        "",
    ]

    runs = manifest.get("runs", {})
    if runs:
        lines += ["### Runs", "", "| claim | attempts | best reward | latest status |", "|---|---|---|---|"]
        for claim_id, attempts in runs.items():
            best = _best_reward(attempts)
            latest = attempts[-1].get("status") if attempts else None
            lines.append(
                f"| `{claim_id}` | {len(attempts)} | {best if best is not None else '—'} "
                f"| {latest or '—'} |"
            )
        lines.append("")
    else:
        lines += ["### Runs", "", "_No attempts yet._", ""]

    return "\n".join(lines)


def write_index(layout: PaperLayout, *, paper_id: str | None = None) -> dict[str, Any]:
    """Regenerate manifest.json + README.md from the current tree. Returns the manifest."""
    layout.root.mkdir(parents=True, exist_ok=True)
    manifest = build_manifest(layout, paper_id=paper_id)
    layout.manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    layout.readme_path.write_text(render_readme(manifest), encoding="utf-8")
    return manifest


def write_run_record(run_dir: str | Path, record: dict[str, Any]) -> Path:
    """Persist a run's metadata as run.json (status/reward/backend/timestamps)."""
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    path = run_dir / "run.json"
    path.write_text(
        json.dumps({"generated_at": _now_iso(), **record}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return path
