"""Generate a BASELINE reward/check.py from a claim spec.

The render contract says check.py is the one hand/agent-authored file (the
build-task skill writes a real metric-recompute verifier). But to keep the
end-to-end loop runnable today, render_check emits a deterministic verdict-trust
baseline: it checks required outputs exist and that output/result.json declares an
allowed verdict, then maps verdict -> reward. It also embeds the CONTRACT dict
validate_task reads, so the rendered task passes the consistency gate. Replace it
with the build-task skill's recompute verifier when available.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from reprogym.pipeline.render_task import derive_contract

DEFAULT_REWARD_BY_VERDICT = {
    "reproduced": 0.8,
    "reproduced_strict": 0.9,
    "failed": 0.35,
    "inconclusive": 0.2,
    "invalid": 0.0,
}

_TEMPLATE = '''#!/usr/bin/env python3
"""BASELINE verifier generated by ReproGym (verdict-trust; replace via build-task skill)."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

CONTRACT = {contract!r}
CLAIM_ID = {claim_id!r}
REQUIRED_FILES = {required_files!r}
ALLOWED_VERDICTS = {verdicts!r}
REWARD_BY_VERDICT = {reward_by_verdict!r}


def verify(workspace: Path) -> dict:
    missing = [f for f in REQUIRED_FILES if not (workspace / f).exists()]
    if missing:
        return {{"reward": 0.0, "verdict": "invalid",
                "errors": ["missing required file: " + m for m in missing]}}
    try:
        result = json.loads((workspace / "output" / "result.json").read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        return {{"reward": 0.0, "verdict": "invalid", "errors": ["unreadable result.json: " + str(exc)]}}

    verdict = result.get("verdict")
    if verdict not in ALLOWED_VERDICTS:
        return {{"reward": 0.0, "verdict": "invalid",
                "errors": ["result.json verdict not allowed: " + repr(verdict)]}}

    reward = float(REWARD_BY_VERDICT.get(verdict, 0.0))
    if verdict == "reproduced" and result.get("strict_reproduction") is True:
        reward = max(reward, float(REWARD_BY_VERDICT.get("reproduced_strict", reward)))
    return {{"reward": round(min(1.0, reward), 6), "verdict": verdict, "errors": []}}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("workspace", nargs="?", default=".")
    parser.add_argument("--reward-only", action="store_true")
    args = parser.parse_args()

    workspace = Path(args.workspace).resolve()
    report = verify(workspace)
    try:
        (workspace / "output").mkdir(exist_ok=True)
        (workspace / "output" / "verification_report.json").write_text(
            json.dumps(report, indent=2, sort_keys=True) + "\\n", encoding="utf-8"
        )
    except Exception:  # noqa: BLE001
        pass

    print(report["reward"] if args.reward_only else json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render_baseline_check_py(spec: dict[str, Any]) -> str:
    c = derive_contract(spec)
    contract = {
        "claim_id": c["claim_id"],
        "metrics": c["metric_names"],
        "thresholds": c["thresholds"],
        "required_files": c["required_files"],
        "verdicts": c["verdicts"],
    }
    reward_by_verdict = dict(DEFAULT_REWARD_BY_VERDICT)
    base = (spec.get("reward") or {}).get("base_by_verdict")
    if isinstance(base, dict):
        reward_by_verdict.update(base)
    return _TEMPLATE.format(
        contract=contract,
        claim_id=c["claim_id"],
        required_files=c["required_files"],
        verdicts=c["verdicts"],
        reward_by_verdict=reward_by_verdict,
    )


def write_baseline_check(spec: dict[str, Any], reward_dir: str | Path) -> Path:
    reward_dir = Path(reward_dir)
    reward_dir.mkdir(parents=True, exist_ok=True)
    out = reward_dir / "check.py"
    out.write_text(render_baseline_check_py(spec), encoding="utf-8")
    return out
